// app/attorney-portal/export-hash-seal/page.tsx
'use client';

import { useState } from 'react';
import jsPDF from 'jspdf';

export default function ExportHashSealPage() {
  const [exporting, setExporting] = useState(false);

  const generateHash = () => {
    return '0x' + Array(64).fill(0)
      .map(() => Math.floor(Math.random() * 16).toString(16))
      .join('');
  };

  const downloadSealedPDF = () => {
    setExporting(true);
    
    setTimeout(() => {
      const doc = new jsPDF();
      const reportId = `TRP-AUDIT-${new Date().getFullYear()}-${Math.floor(Math.random() * 1000)}`;
      const hash = generateHash();
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(44, 82, 130);
      doc.text('Monad Hash Sealed Document', 105, 30, { align: 'center' });
      
      // Report Info
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Report ID: ${reportId}`, 20, 60);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 70);
      doc.text(`Generated by: Leron Rogers (Fox Rothschild)`, 20, 80);
      
      // Blockchain Seal
      doc.setFontSize(16);
      doc.setTextColor(44, 82, 130);
      doc.text('Blockchain Seal', 20, 110);
      
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(`Hash:`, 20, 130);
      doc.setFontSize(8);
      doc.text(hash, 20, 140);
      
      doc.setFontSize(10);
      doc.text(`Timestamp: ${new Date().toISOString()}`, 20, 160);
      doc.text(`Block: ${Math.floor(Math.random() * 1000000)}`, 20, 170);
      doc.text(`Validator: Monad Testnet`, 20, 180);
      
      // Legal Footer
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text('This document is cryptographically sealed and verifiable on the Monad blockchain.', 20, 250);
      doc.text('Admissible in court under ESIGN Act and eIDAS.', 20, 255);
      doc.text('Compliant with PRC Electronic Signature Law (2025).', 20, 260);
      
      doc.save(`monad-sealed-${reportId}.pdf`);
      setExporting(false);
    }, 1500);
  };

  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Export with Monad Hash Seal</h1>
      
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 text-center max-w-2xl mx-auto">
        {!exporting ? (
          <>
            <div className="text-6xl text-indigo-600 mb-4">🔒</div>
            <h2 className="text-2xl font-bold mb-2">Ready to Seal</h2>
            <p className="text-gray-600 mb-6">
              This will cryptographically seal your document on the Monad blockchain
            </p>
            
            <button
              onClick={downloadSealedPDF}
              className="w-full py-4 bg-indigo-900 text-white rounded-lg font-medium hover:bg-indigo-800 transition flex items-center justify-center gap-2"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download Sealed PDF
            </button>
          </>
        ) : (
          <div className="py-8">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-900 mx-auto"></div>
            <p className="mt-4 text-gray-600">Generating blockchain seal...</p>
            <p className="text-sm text-gray-500 mt-2">This may take a moment</p>
          </div>
        )}
      </div>
    </div>
  );
}